version: "3"
services:
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user_id: 1005
    entrypoint: /bin/bash /home/jovyan/work/start-notebook.sh
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./:/home/jovyan/work
      - ~/.gitconfig:/etc/gitconfig
      - ~/data:/data
    ports:
      - "8801:8888" # Jupyter
    expose:
      - "8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
