version: "3"
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user_id: 1005
    volumes:
      - ./:/home/user
      - ~/.gitconfig:/etc/gitconfig
      - ~/data:/data
    ports:
      - "8801:8888" # Jupyter
    expose:
      - "8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  rstudio-server:
      build:
          context: ./
          dockerfile: Dockerfile-rstudio
      ports:
          - "8802:8787"
          - "8838:3838"
      environment:
          - USER=victor # *
          - USERID=1005 # *
          - GROUPID=1005 # *
          - PASSWORD=asd # *
          - ROOT=TRUE
          - ADD=shiny
      volumes:
         - ./r_shiny_app:/home/victor
         - /home/victor/data:/data
         - ./pacmel_mining_use_case:/project_lib