version: "3"
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID} #* 
        - GROUP_ID=${GROUP_ID} #* Important to define it to work with Pacmel Data hosted in UPM servers (This is the group id of the user in which the folder where pacmel data is shared is located) 
        - USER=${USER_NAME} #*
    ports:
      - "${JUPYTER_PORT}:8888" #*
    expose:
      - "8888"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY} #*
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
      - GH_TOKEN=${GH_TOKEN}
      - WANDB_DIR=/home/${USER_NAME}/work
    volumes:
      - ./:/home/${USER_NAME}/work #*
      - ~/.gitconfig:/etc/gitconfig # Need to create this file
      - ${LOCAL_DATA_PATH}:/home/${USER_NAME}/data/ #*
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
  rstudio-server:
      build:
          context: ./
          dockerfile: Dockerfile-rstudio
          args:
              - WANDB_API_KEY=${WANDB_API_KEY} #*
      ports:
          - "${RSTUDIO_PORT}:8787" #*
      environment:
          - USER=${USER_NAME} #* 
          - USERID=${USER_ID} #*
          - GROUPID=${GROUP_ID} #*
          - PASSWORD=${RSTUDIO_PASSWD} #*
          - ROOT=TRUE
      volumes:
         - ./r_shiny_app:/home/${USER_NAME} #*
         - ${LOCAL_DATA_PATH}:/data/ #*
         - ./timecluster_extension:/project_lib # No se usa aun
