services:
  jupyter:
    build:
      args:
        - username=${USER_NAME}
        - uid=${USER_ID}
        - gid=${GROUP_ID}
      context: ../
      dockerfile: Dockerfile-conda
    ports:
      - "${JUPYTER_PORT}:8888"
    runtime: nvidia
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY} #*
      - GH_TOKEN=${GH_TOKEN} #*
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
      - WANDB_DIR=/home/${USER_NAME}/work
    volumes:
      - ../../:/home/${USER}/work
      - ${LOCAL_DATA_PATH}:/home/${USER_NAME}/data/ #*
      - conda-env:/home/${USER_NAME}/env
      - miniconda:/home/${USER_NAME}/miniconda3
      - lib:/home/${USER_NAME}/lib
    init: true
    stdin_open: true
    tty: true    
  rstudio-server:
      build:
          context: ../../
          dockerfile: Dockerfile-rstudio-conda
          args:
              - WANDB_API_KEY=${WANDB_API_KEY} #
              - RETICULATE_PYTHON_ENV=/home/${USER_NAME}/env
              - RETICULATE_MINICONDA_PATH=/home/${USER_NAME}/miniconda3
              - USER=${USER_NAME} #* 
              - UID=${USER_ID} #*
              - GID=${GROUP_ID} #*
      ports:
          - "${RSTUDIO_PORT}:8787" #*
      environment:
          - USER=${USER_NAME} #* 
          - USERID=${USER_ID} #*
          - GROUPID=${GROUP_ID} #*
          - PASSWORD=${RSTUDIO_PASSWD} #*
          - ROOT=FALSE
          - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
          - GH_TOKEN=${GH_TOKEN} #*
      runtime: nvidia
      volumes:
         - ../../r_shiny_app:/home/${USER_NAME}/app #*
         - ${LOCAL_DATA_PATH}:/home/${USER_NAME}/data/ #*
         - ../../tchub:/home/${USER_NAME}/tchub # No se usa aun
         - conda-env:/home/${USER_NAME}/env:ro
         - miniconda:/home/${USER_NAME}/miniconda3:ro
         - lib:/home/${USER_NAME}/lib:ro

volumes:
  conda-env:
  miniconda:
  lib:
